### ISSUE TITLE
For chapter 10 solution, which class(es) was edited and what piece of code was added?

### ISSUE THREAD

**Issue by akapoor47** [markon/big-nerd-ranch-android-programming-2nd#1]
If there is a separate pull request only for Chapter 10 challenge, please share.

**Comment by markon** [comment]
Hello @akapoor47, if you have a look at the commit https://github.com/markon/big-nerd-ranch-android-programming-2nd/commit/6b883d54bd3349623c6cb37722fc9f94ed15cada#diff-053939cbf297485499d6ad4526e854f8, you will see a call to "notifyItemChanged". Therefore, I would suggest you to take a look mainly at that class.
